# Generated by Django 5.0.2 on 2024-03-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('users_and_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='participants',
            field=models.ManyToManyField(to='users_and_profiles.profile'),
        ),
    ]
