# Generated by Django 5.0.2 on 2024-04-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
